import { bookingResType } from '@/schemaValidations/table.schema';

const mockBookings: bookingResType[] = [
    {
        id: 1,
        username: 'Nguyễn Văn A',
        phoneNumber: '0912345678',
        bookingDate: '2025-05-10',
        bookingTime: '18:30',
        members: 4,
        branch: 'Chi nhánh Quận 1',
        status: 'confirmed',
        userNote: 'Tôi muốn ngồi gần cửa sổ.',
        adminNote: 'Khách hàng quen thuộc.',
    },
    {
        id: 2,
        username: 'Trần Thị B',
        phoneNumber: '0987654321',
        bookingDate: '2025-05-11',
        bookingTime: '19:00',
        members: 2,
        branch: 'Chi nhánh Quận 3',
        status: 'pending',
        userNote: 'Vui lòng chuẩn bị bánh sinh nhật.',
        adminNote: '',
    },
    {
        id: 3,
        username: 'Lê Hoàng C',
        phoneNumber: '0933111222',
        bookingDate: '2025-05-12',
        bookingTime: '12:00',
        members: 5,
        branch: 'Chi nhánh Bình Thạnh',
        status: 'cancelled',
        userNote: 'Sẽ đến trễ 10 phút.',
        adminNote: 'Đã hủy vì khách không đến.',
    },
    {
        id: 4,
        username: 'Phạm Minh D',
        phoneNumber: '0901234567',
        bookingDate: '2025-05-13',
        bookingTime: '17:30',
        members: 3,
        branch: 'Chi nhánh Thủ Đức',
        status: 'confirmed',
    },
    {
        id: 5,
        username: 'Đỗ Thị E',
        phoneNumber: '0923456789',
        bookingDate: '2025-05-14',
        bookingTime: '20:00',
        members: 6,
        branch: 'Chi nhánh Gò Vấp',
        status: 'pending',
        userNote: 'Có trẻ em đi cùng.',
    },
    {
        id: 6,
        username: 'Huỳnh Văn F',
        phoneNumber: '0944556677',
        bookingDate: '2025-05-15',
        bookingTime: '11:00',
        members: 1,
        branch: 'Chi nhánh Quận 5',
        status: 'confirmed',
        userNote: 'Chỗ ngồi yên tĩnh.',
    },
    {
        id: 7,
        username: 'Ngô Thị G',
        phoneNumber: '0977888999',
        bookingDate: '2025-05-16',
        bookingTime: '13:45',
        members: 2,
        branch: 'Chi nhánh Phú Nhuận',
        status: 'cancelled',
        userNote: 'Đổi lịch sang tuần sau.',
        adminNote: 'Khách hẹn lại.',
    },
    {
        id: 8,
        username: 'Vũ Hoàng H',
        phoneNumber: '0966112233',
        bookingDate: '2025-05-17',
        bookingTime: '15:30',
        members: 8,
        branch: 'Chi nhánh Tân Bình',
        status: 'confirmed',
        adminNote: 'Sự kiện nhóm công ty.',
    },
    {
        id: 9,
        username: 'Bùi Thị I',
        phoneNumber: '0955667788',
        bookingDate: '2025-05-18',
        bookingTime: '10:00',
        members: 2,
        branch: 'Chi nhánh Quận 7',
        status: 'pending',
        userNote: 'Tôi sẽ gọi lại để xác nhận.',
    },
    {
        id: 10,
        username: 'Cao Văn K',
        phoneNumber: '0933221100',
        bookingDate: '2025-05-19',
        bookingTime: '16:00',
        members: 3,
        branch: 'Chi nhánh Quận 10',
        status: 'confirmed',
        userNote: 'Ăn chay.',
        adminNote: 'Thông báo bếp trước.',
    },
];

export default mockBookings;

export const mockPendingBookings: bookingResType[] = [
    {
        id: 1,
        username: 'Nguyễn Thị L',
        phoneNumber: '0911222333',
        bookingDate: '2025-05-21',
        bookingTime: '18:00',
        members: 2,
        branch: 'Chi nhánh Quận 1',
        status: 'pending',
        userNote: 'Muốn ngồi tầng trên.',
    },
    {
        id: 2,
        username: 'Trần Văn M',
        phoneNumber: '0922333444',
        bookingDate: '2025-05-22',
        bookingTime: '19:30',
        members: 4,
        branch: 'Chi nhánh Quận 3',
        status: 'pending',
        adminNote: 'Chưa xác nhận.',
    },
    {
        id: 3,
        username: 'Lê Thị N',
        phoneNumber: '0933444555',
        bookingDate: '2025-05-23',
        bookingTime: '17:00',
        members: 3,
        branch: 'Chi nhánh Bình Thạnh',
        status: 'pending',
    },
    {
        id: 4,
        username: 'Phạm Văn O',
        phoneNumber: '0944555666',
        bookingDate: '2025-05-24',
        bookingTime: '20:15',
        members: 5,
        branch: 'Chi nhánh Thủ Đức',
        status: 'pending',
        userNote: 'Có người lớn tuổi đi cùng.',
    },
    {
        id: 5,
        username: 'Đỗ Thị P',
        phoneNumber: '0955666777',
        bookingDate: '2025-05-25',
        bookingTime: '11:45',
        members: 1,
        branch: 'Chi nhánh Gò Vấp',
        status: 'pending',
        adminNote: 'Chờ xác nhận từ bộ phận lễ tân.',
    },
];
