import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import GlobalStyle from "@/components/GlobalStyle/GlobalStyle";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalStyle>
      <html lang="en">
        <body className={` ${spaceGrotesk.variable} antialiased`}>
          {children}
        </body>
      </html>
    </GlobalStyle>
  );
}
